[package]
name = "bouncer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
tokio = { version = "1", features = [ "full" ] }
xxhash-rust = { version = "0.8.6", features = [ "xxh3" ] }
log = "*"
env_logger = "0.10.0"

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk.git"
rev = "0b9c082e"
default-features = false
features = [ "rustls-tls", "anyhow" ]
